version: "3.8"
services:
  dacs_gateway:
    image: "kyberneees/rproxy:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/config.js:/rproxy/src/config.js
    hostname: "dacs_gateway"
  dacs_fe:
    build: .
    ports:
      - "3000:3000"
    hostname: "dacs_fe"
