export const sessionActions = {
  SET_CURRENT_USER_INFO: 'SESSION/SET_CURRENT_USER_INFO',
  LOGOUT: 'SESSION/LOGOUT',
  FORGOT_PASSWORD: 'SESSION/FORGOT_PASSWORD',
  RESET_PASSWORD: 'SESSION/RESET_PASSWORD',
};

export const requestActions = {
  REQUEST: 'REQUEST/REQUEST',
  FAILED: 'REQUEST/FAILED',
  SUCCESS: 'REQUEST/SUCCESS',
};

export const actionTypes = {
  CREATE_USER: 'ACTION/CREATE_USER',
  DELETE_USER: 'ACTION/DELETE_USER',
  SAVE_USER_SETTINGS: 'ACTION/SAVE_USER_SETTINGS',
  CHANGE_USER_PASSWORD: 'ACTION/CHANGE_USER_PASSWORD',
  GET_PAYMENTS: 'ACTION/GET_PAYMENTS',
  ASSIGN_PAYMENT: 'ACTION/ASSIGN_PAYMENT',
  NULLIFY_PAYMENTS: 'ACTION/NULLIFY_PAYMENT',
  CONFIRM_PAYMENTS: 'ACTION/CONFIRM_PAYMENTS',
  GET_INSCRIPTIONS: 'ACTION/GET_INSCRIPTIONS',
  FIND_STUDENT: 'ACTION/FIND_STUDENT',
  FIND_FEE: 'ACTION/FIND_FEE',
  FIND_STUDENT_FEES: 'ACTION/FIND_STUDENT_FEES',
  UPDATE_FEES: 'ACTION/UPDATE_FEES',
  DELETE_FEES: 'ACTION/DELETE_FEES',
  GET_STUDENTS: 'ACTION/GET_STUDENTS',
  UPDATE_EMAIL: 'ACTION/UPDATE_EMAIL',
  UPDATE_ENABLED: 'ACTION/UPDATE_ENABLED',
  PROCESS_SPREADSHEETS: 'ACTION/PROCESS_SPREADSHEETS',
  GET_USERS: 'ACTION/GET_USERS',
  GET_SYSTUP: 'ACTION/GET_SYSTUP',
  GET_REPORTETOTAL: 'ACTION/GET_REPORTETOTAL',
  GET_REPORTEANUAL: 'ACTION/GET_REPORTEANUAL',
  GET_REPORTEMENSUAL: 'ACTION/GET_REPORTEMENSUAL',
  GET_REPORTETOTMENSUAL: 'ACTION/GET_REPORTETOTMENSUAL',
};
